# Generated by Django 5.0.9 on 2025-04-05 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DisparadorApp', '0003_campanha_hora_inicio_campanha_hora_termino_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracao',
            name='hora_fim',
        ),
        migrations.RemoveField(
            model_name='configuracao',
            name='hora_inicio',
        ),
    ]
