# Generated by Django 5.0.9 on 2025-04-05 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DisparadorApp', '0004_remove_configuracao_hora_fim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20)),
                ('variavel_a', models.CharField(blank=True, max_length=255, null=True)),
                ('variavel_b', models.CharField(blank=True, max_length=255, null=True)),
                ('variavel_c', models.CharField(blank=True, max_length=255, null=True)),
                ('variavel_d', models.CharField(blank=True, max_length=255, null=True)),
                ('enviado', models.BooleanField(default=False)),
                ('data_envio', models.DateTimeField(blank=True, null=True)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados', to='DisparadorApp.campanha')),
            ],
        ),
    ]
