# Generated by Django 5.0.9 on 2025-04-05 01:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DisparadorApp', '0005_dados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(8, 0), null=True),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='hora_termino',
            field=models.TimeField(blank=True, default=datetime.time(18, 0), null=True),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='mensagem',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='status',
            field=models.CharField(blank=True, choices=[('agendada', 'Agendada'), ('ativa', 'Ativa'), ('finalizada', 'Finalizada')], default='agendada', max_length=20, null=True),
        ),
    ]
