# Generated by Django 5.0.9 on 2025-04-11 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DisparadorApp', '0006_alter_campanha_data_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='erro_envio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='status',
            field=models.CharField(blank=True, choices=[('agendada', 'Agendada'), ('emexecucao', 'Em Execução'), ('finalizada', 'Finalizada')], default='agendada', max_length=20, null=True),
        ),
    ]
